# Configuration Jekyll basique
title: Mon site web
baseurl: ""
theme: jekyll-theme-primer
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

  theme: jekyll-theme-primer
gems:
  - jekyll-github-metadata
  - jekyll-seo-tag
  # autres plugins...


# Configuration Python (ajoutez cette ligne si nécessaire)
python:
  - python3
