name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Configurer Python et créer un environnement virtuel
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install Python dependencies
      run: |
        python -m venv myenv  # Crée l'environnement virtuel
        source myenv/bin/activate  # Active l'environnement virtuel
        pip install -r requirements.txt  # Installe les dépendances Python nécessaires

    # Construire et déployer avec Jekyll
    - name: Install Jekyll dependencies
      run: |
        bundle install  # Installe les dépendances Jekyll
        bundle exec jekyll build  # Génère le site avec Jekyll

    # Exécuter des étapes supplémentaires si nécessaire
