name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Spécifiez la version de Python requise

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown # 

    - name: Build site
      run: |
        pelican content -s pelicanconf.py # Générez le site avec Pelican

    - name: Deploy
      run: |
        # Ajoutez les étapes de déploiement appropriées ici
        echo "Déploiement à configurer ici"

