name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Met à jour vers v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Version stable la plus récente
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jekyll

      - name: Build site
        run: |
          jekyll build

      - name: Deploy
        run: |
          # Ajoutez ici les commandes pour déployer votre site, par exemple :
          # gh-pages -d _site
